package com.bellfamily.bastischool.audio

import com.bellfamily.bastischool.learning.models.ContentLanguage
import com.bellfamily.bastischool.learning.models.ContentText
import com.bellfamily.bastischool.learning.models.LocalizedText

enum class AudioMode { ALL, QUESTIONS, OFF }
enum class SpeechTrigger { AUTOMATIC, REPLAY, MANUAL }
enum class SpeechKind(val instructional: Boolean) {
    INSTRUCTION(true), QUESTION(true), TUTORIAL(true), EXPLANATION(true),
    OPTION(false), FEEDBACK(false), COMPLETION(false), DISCOVERY_FACT(false), CHARACTER_LINE(false)
}

/** Responses supersede delayed instructions within one context; nothing is queued. */
enum class SpeechPriority { INSTRUCTION, RESPONSE }

fun AudioMode.allows(kind: SpeechKind, trigger: SpeechTrigger): Boolean = when (this) {
    AudioMode.ALL -> true
    AudioMode.QUESTIONS -> trigger != SpeechTrigger.AUTOMATIC || kind.instructional
    AudioMode.OFF -> false
}

data class SpeechOwner(val value: String) { init { require(value.isNotBlank()) } }
data class SpeechSessionId(val value: String) { init { require(value.isNotBlank()) } }

/** Opaque, revocable token. Open a fresh context for each task/phase/language or destination return. */
class SpeechContext internal constructor(
    val owner: SpeechOwner,
    val session: SpeechSessionId,
    val language: ContentLanguage
)

/** Generated by the controller, never reused there, including for identical Replay taps. */
class SpeechRequestId internal constructor(val value: Long) {
    override fun toString() = "speech-$value"
}

data class SpeechRequest(
    val context: SpeechContext,
    val speechText: String,
    val kind: SpeechKind,
    val trigger: SpeechTrigger = SpeechTrigger.AUTOMATIC
) {
    val priority: SpeechPriority get() =
        if (trigger == SpeechTrigger.AUTOMATIC && kind.instructional) SpeechPriority.INSTRUCTION
        else SpeechPriority.RESPONSE

    companion object {
        fun fromContent(context: SpeechContext, text: ContentText, kind: SpeechKind,
                        trigger: SpeechTrigger = SpeechTrigger.AUTOMATIC) =
            fromLocalized(context, text.speech, kind, trigger)

        /** For separately authored descriptions as well as short spoken labels. Never display fallback. */
        fun fromLocalized(context: SpeechContext, speech: LocalizedText, kind: SpeechKind,
                          trigger: SpeechTrigger = SpeechTrigger.AUTOMATIC) =
            SpeechRequest(context, speech[context.language], kind, trigger)
    }
}

enum class SpeechFailure { ENGINE_UNAVAILABLE, MISSING_OFFLINE_VOICE, VOICE_SELECTION, PLAYBACK, EMPTY_TEXT }
enum class SpeechCancellation { REPLACED, CONTEXT_CHANGED, OWNER_LEFT, SESSION_ENDED, REQUESTED, POLICY_CHANGED, ENGINE_STOPPED, CLOSED }
enum class SpeechSuppression { POLICY, STALE_CONTEXT, LOWER_PRIORITY, CLOSED }
sealed interface SpeechResult {
    data object Completed : SpeechResult
    data class Failed(val reason: SpeechFailure) : SpeechResult
    data class Cancelled(val reason: SpeechCancellation) : SpeechResult
    data class Suppressed(val reason: SpeechSuppression) : SpeechResult
}

data class SpeechOutcome(val id: SpeechRequestId, val result: SpeechResult)

/** Result remains null while waiting/playing; terminal results are written exactly once. */
class SpeechTicket internal constructor(val id: SpeechRequestId) {
    var result: SpeechResult? = null
        internal set
}

enum class EngineReadiness { INITIALISING, READY, FAILED, CLOSED }
sealed interface EngineResult {
    data object Completed : EngineResult
    data object Cancelled : EngineResult
    data class Failed(val reason: SpeechFailure) : EngineResult
}

/** Only the controller creates these after policy and sanitation. */
class EngineSpeechRequest internal constructor(
    val id: SpeechRequestId,
    val context: SpeechContext,
    val text: String,
    val kind: SpeechKind,
    val trigger: SpeechTrigger
)

/** One controller exclusively owns one engine. Calls and callbacks use the same serialized thread. */
interface SpeechEngine {
    val readiness: EngineReadiness
    var onReadinessChanged: ((EngineReadiness) -> Unit)?
    fun speak(request: EngineSpeechRequest, result: (EngineResult) -> Unit)
    fun stop()
    fun close()
}

interface AudioController {
    val mode: AudioMode
    val readiness: EngineReadiness
    fun openContext(owner: SpeechOwner, session: SpeechSessionId, language: ContentLanguage): SpeechContext
    fun speak(request: SpeechRequest, onResult: (SpeechOutcome) -> Unit = {}): SpeechTicket
    fun setMode(mode: AudioMode)
    fun cancelRequest(id: SpeechRequestId)
    fun cancelOwner(owner: SpeechOwner)
    fun cancelSession(session: SpeechSessionId)
    fun close()
}
